name: ci

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  ci:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        version: [stable, nightly]
    outputs:
      image: ${{ steps.build.outputs.image }}
    steps:
      - name: Install dependencies
        id: install-dependencies
        run: |
          sudo apt-get update -qqq
          sudo apt-get install -yqqq haproxy
      - name: Install Rust
        id: install-rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.version }}
          profile: minimal
          components: rustfmt, clippy
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Build
        id: build
        run: cargo b --examples
      - name: Test extract
        id: test-extract
        run: sh ci/extract.sh
      - name: Test PROXY v1
        id: test-proxy-v1
        run: sh ci/proxy-v1.sh
      - name: Test PROXY v2
        id: test-proxy-v2
        run: sh ci/proxy-v2.sh
      - name: Lint (format)
        id: lint-fmt
        run: cargo fmt --check
      - name: Lint (clippy)
        id: lint-clippy
        run: cargo clippy --offline
      - name: Cache
        if: ${{ (github.event_name == 'release' && ! github.event.release.prerelease && ! github.event.release.draft) || matrix.version == 'nightly' }}
        id: cache
        uses: actions/upload-artifact@v4
        with:
          name: target-${{ matrix.version }}
          path: target
          compression-level: 0
          retention-days: 1
  publish:
    runs-on: ubuntu-24.04
    if: ${{ github.event_name == 'release' && ! github.event.release.prerelease && ! github.event.release.draft }}
    steps:
    - name: Install Rust
      id: install-rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
    - name: Check out the repository to the runner
      uses: actions/checkout@v4
    - name: Cache
      uses: actions/download-artifact@v4
      with:
        name: target-stable
        merge-multiple: true
    - name: Publish crate
      id: publish-crate
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: |
        cargo publish
